ethereum:
  nodes:
    - name: default
      url: ws://your-node-host
      # username: my-username
      # password: my-password

broadcaster:
  type: PULSAR

pulsar:
  # See https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ClientConfigurationData.java
  # for available options
  config:
    serviceUrl: pulsar://localhost:6650

  # To enable authentication, uncomment this following section
  # authentication:
  #   plugin-class-name: org.apache.pulsar.client.impl.auth.AuthenticationBasic
  #   params:
  #     userId: my-username
  #     password: my-password

  # Topic can also be set to 'just the name' (which will default to tenant 'public' and namespace 'default')
  topic:
    blockEvents: persistent://public/default/block-events
    contractEvents: persistent://public/default/contract-events
    transactionEvents: persistent://public/default/transaction-events
