spring:
  # docker run -d --name sql_server_demo -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=reallyStrongPwd123' -p 1433:1433 microsoft/mssql-server-linux
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=eventeum
    username: sa
    password: reallyStrongPwd123
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        #see: https://stackoverflow.com/questions/36583185/spring-data-jpa-could-not-initialize-proxy-no-session-with-methods-marke
        enable_lazy_load_no_trans: true
        # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update
#     jdbc:
#       lob:
#         # For postgres, see: https://github.com/pgjdbc/pgjdbc/issues/1102
#         non_contextual_creation: true

database:
  type: SQL
